In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals
import os

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf


TensorFlow 2.x selected.


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving shakespeare.txt to shakespeare.txt


In [ ]:
import os

In [ ]:
path_to_file = 'shakespeare.txt'

In [ ]:
text = open(path_to_file,'r').read()

In [ ]:
print(text[140500:141500])

reward.
  HELENA. Inspired merit so by breath is barr'd.
    It is not so with Him that all things knows,
    As 'tis with us that square our guess by shows;
    But most it is presumption in us when
    The help of heaven we count the act of men.
    Dear sir, to my endeavours give consent;
    Of heaven, not me, make an experiment.
    I am not an impostor, that proclaim  
    Myself against the level of mine aim;
    But know I think, and think I know most sure,
    My art is not past power nor you past cure.
  KING. Art thou so confident? Within what space
    Hop'st thou my cure?
  HELENA. The greatest Grace lending grace.
    Ere twice the horses of the sun shall bring
    Their fiery torcher his diurnal ring,
    Ere twice in murk and occidental damp
    Moist Hesperus hath quench'd his sleepy lamp,
    Or four and twenty times the pilot's glass
    Hath told the thievish minutes how they pass,
    What is infirm from your sound parts shall fly,
    Health shall live free, and s

In [ ]:
vocab = sorted(set(text))
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [ ]:
len(vocab) #all unique characters

84

In [ ]:
for pair in enumerate(vocab): #for loop using enumerate for list and printing out the iterating thing creates tuples
  print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [ ]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [ ]:
char_to_ind['H']

33

In [ ]:
ind_to_char = np.array(vocab)
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [ ]:
ind_to_char[33]

'H'

In [ ]:
encoded_text = np.array([char_to_ind[c] for c in text]) 

In [ ]:
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [ ]:
encoded_text.shape #over 5 mil chars

(5445609,)

In [ ]:
sample = text[:500]
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [ ]:
print(sample)


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [ ]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [ ]:
line =  "From fairest creatures we desire increase"
len(line)

41

In [ ]:
lines = '''
From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
'''
#multiple lines
len(lines)

133

In [ ]:
seq_len = 120

In [ ]:
total_num_seq = len(text)/(seq_len+1)
total_num_seq

45005.03305785124

In [ ]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [ ]:
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [ ]:
tf.executing_eagerly()

True

In [ ]:
for item in char_dataset.take(500): #requires eager execution. its why we did weird thing at top with tensorflow importing to get tensorflow 2
  print(item.numpy())

0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
12
0
1
1
31
73
70
68
1
61
56
64
73
60
74
75
1
58
73
60
56
75
76
73
60
74
1
78
60
1
59
60
74
64
73
60
1
64
69
58
73
60
56
74
60
8
0
1
1
45
63
56
75
1
75
63
60
73
60
57
80
1
57
60
56
76
75
80
5
74
1
73
70
74
60
1
68
64
62
63
75
1
69
60
77
60
73
1
59
64
60
8
0
1
1
27
76
75
1
56
74
1
75
63
60
1
73
64
71
60
73
1
74
63
70
76
67
59
1
57
80
1
75
64
68
60
1
59
60
58
60
56
74
60
8
0
1
1
33
64
74
1
75
60
69
59
60
73
1
63
60
64
73
1
68
64
62
63
75
1
57
60
56
73
1
63
64
74
1
68
60
68
70
73
80
21
0
1
1
27
76
75
1
75
63
70
76
1
58
70
69
75
73
56
58
75
60
59
1
75
70
1
75
63
64
69
60
1
70
78
69
1
57
73
64
62
63
75
1
60
80
60
74
8
0
1
1
31
60
60
59
5
74
75
1
75
63
80
1
67
64
62
63
75
5
74
1
61
67
56
68
60
1
78
64
75
63
1
74
60
67
61
9
74
76
57
74
75
56
69
75
64
56
67
1
61
76
60
67
8
0
1
1
38
56
66
64
69
62
1
56
1
61
56
68
64
69
60
1
78
63
60
73
60
1
56
57
76
69
59
56
69
58
60
1
67
64
60
74
8
0
1
1
45
63
80
1
74
60
67
61
1
75
63
80
1
61
70
60
8
1
75
70
1
75
63


In [ ]:
for item in char_dataset.take(500): #requires eager execution. its why we did weird thing at top with tensorflow importing to get tensorflow 2
  print(ind_to_char[item.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [ ]:
#char_dataset is encoded
sequences = char_dataset.batch(seq_len+1,drop_remainder=True) #discards remaining characters. cuz obv our text doesnt perfectly divide perfectly by 120. bye bye remainder

In [ ]:
def create_seq_targets(seq):
  input_txt = seq[:-1] #['h','e','l','l']
  target_txt = seq[1:] #['e','l','l','o']
  return input_txt,target_txt

In [ ]:
dataset = sequences.map(create_seq_targets) #mapping the function to our sequences

In [ ]:
for input_txt,target_txt in dataset.take(1):
  print(input_txt.numpy())
  print("".join(ind_to_char[input_txt.numpy()]))
  print('\n')
  print(target_txt.numpy())
  print("".join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [ ]:
batch_size = 128

In [ ]:
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

In [ ]:
vocab_size = len(vocab)

In [ ]:
embed_dim = 64

In [ ]:
rnn_neurons = 1026

In [ ]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [ ]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module tensorflow.python.keras.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    Args:
      y_true: Ground truth values.
      y_pred: The predicted values.
      from_logits: Whether `y_pred` is expected to be a logits tensor. By default,
        we assume that `y_pred` encodes a probability distribution.
      axis: (Optional) Defaults to -1. The dimension along which the entropy is
        computed.
    
    Returns:
      Sparse categorical crossentropy loss value.



In [ ]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GRU

In [ ]:
def create_model(vocab_size,embed_dim,rnn_neurons,batch_size): 
  model = Sequential()

  model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[batch_size,None]))
  model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
  model.add(Dense(vocab_size))
  model.compile('adam',loss=sparse_cat_loss) 
  return model

In [ ]:
model = create_model(vocab_size=vocab_size,
                     embed_dim=embed_dim,
                     rnn_neurons=rnn_neurons,
                     batch_size=batch_size) 

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1026)         3361176   
_________________________________________________________________
dense (Dense)                (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [ ]:
for input_example_batch, target_example_batch in dataset.take(1):

  example_batch_predictions = model(input_example_batch)

In [ ]:
example_batch_predictions.shape #number of things(batch size), sequence length, vocab size

TensorShape([128, 120, 84])

In [ ]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 0.00223091, -0.00138323,  0.00283006, ..., -0.00373639,
        -0.00701475, -0.00140882],
       [-0.00360761,  0.00396621,  0.00481691, ..., -0.00080167,
        -0.00711367, -0.00345094],
       [ 0.00186118,  0.00136678,  0.00599901, ..., -0.00422146,
        -0.00977436, -0.00295338],
       ...,
       [ 0.00549306, -0.00429622,  0.0004429 , ...,  0.00767957,
        -0.00696413,  0.00487974],
       [ 0.00662732, -0.00276699,  0.00513185, ...,  0.00454545,
        -0.00546218,  0.00558195],
       [-0.00841364,  0.00303265,  0.00180447, ...,  0.00021926,
        -0.00023777,  0.00206445]], dtype=float32)>

In [ ]:
sampled_indices = tf.random.categorical(example_batch_predictions[0],num_samples=1)
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[10],
       [23],
       [20],
       [ 4],
       [50],
       [ 3],
       [10],
       [50],
       [62],
       [ 0],
       [66],
       [26],
       [49],
       [63],
       [21],
       [50],
       [80],
       [52],
       [39],
       [51],
       [46],
       [83],
       [17],
       [28],
       [33],
       [18],
       [41],
       [42],
       [21],
       [77],
       [47],
       [70],
       [ 1],
       [53],
       [21],
       [43],
       [28],
       [41],
       [20],
       [69],
       [27],
       [36],
       [34],
       [15],
       [65],
       [68],
       [70],
       [33],
       [10],
       [35],
       [66],
       [65],
       [10],
       [ 9],
       [16],
       [ 0],
       [60],
       [37],
       [56],
       [20],
       [83],
       [ 0],
       [74],
       [45],
       [40],
       [13],
       [21],
       [38],
       [27],
       [74],
       [58],
       [31],
       [47],
   

In [ ]:
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()
ind_to_char[sampled_indices] #hasnt been trained so obviously the predictions are random

array(['.', '<', '9', '&', 'Y', '"', '.', 'Y', 'g', '\n', 'k', 'A', 'X',
       'h', ':', 'Y', 'y', '[', 'N', 'Z', 'U', '}', '6', 'C', 'H', '7',
       'P', 'Q', ':', 'v', 'V', 'o', ' ', ']', ':', 'R', 'C', 'P', '9',
       'n', 'B', 'K', 'I', '4', 'j', 'm', 'o', 'H', '.', 'J', 'k', 'j',
       '.', '-', '5', '\n', 'e', 'L', 'a', '9', '}', '\n', 's', 'T', 'O',
       '2', ':', 'M', 'B', 's', 'c', 'F', 'V', 'o', 'b', '<', 'm', 'W',
       'm', 'R', 'R', 'Z', 'h', '>', 'h', 'N', 'u', 'q', 'I', 'k', 'E',
       'm', 'L', 'N', '5', '(', 's', 'b', ',', 'w', 'C', 'w', 'X', '>',
       'D', 't', ',', '&', '2', '\n', 'f', 'R', 'L', 'V', 'k', 'N', 'p',
       '!', 'n', 'a'], dtype='<U1')

In [ ]:
epochs=30

model.fit(dataset,epochs=epochs)

Epoch 1/30
351/351 [==============================] - 49s 140ms/step - loss: 2.5331
Epoch 2/30
351/351 [==============================] - 51s 146ms/step - loss: 1.7517
Epoch 3/30
351/351 [==============================] - 52s 149ms/step - loss: 1.4722
Epoch 4/30
351/351 [==============================] - 53s 150ms/step - loss: 1.3476
Epoch 5/30
351/351 [==============================] - 52s 147ms/step - loss: 1.2824
Epoch 6/30
351/351 [==============================] - 53s 150ms/step - loss: 1.2417
Epoch 7/30
351/351 [==============================] - 52s 149ms/step - loss: 1.2110
Epoch 8/30
351/351 [==============================] - 52s 148ms/step - loss: 1.1870
Epoch 9/30
351/351 [==============================] - 53s 150ms/step - loss: 1.1670
Epoch 10/30
351/351 [==============================] - 53s 151ms/step - loss: 1.1489
Epoch 11/30
351/351 [==============================] - 53s 151ms/step - loss: 1.1329
Epoch 12/30
351/351 [==============================] - 52s 148ms/step - lo

In [ ]:
from tensorflow.keras.models import load_model

In [ ]:
model.save('shakespeare_gen.h5')

In [ ]:
model2 = create_model(vocab_size,embed_dim,rnn_neurons,batch_size=1) #new untrained model

model2.load_weights('shakespeare_gen.h5')

model2.build(tf.TensorShape([1,None]))

In [ ]:
model2.summary() #yeee

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (1, None, 64)             5376      
_________________________________________________________________
gru_4 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_4 (Dense)              (1, None, 84)             86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [ ]:
def generate_text(model,start_seed,gen_size=500,temp=1.0): #u can specify stuff for gen_size and temp, or leave it at these defaults

  num_generate = gen_size

  input_eval = [char_to_ind[s] for s in start_seed]
  
  input_eval = tf.expand_dims(input_eval,0)

  text_generated = []

  temperature = temp 

  model.reset_states()

  for i in range(num_generate):

    predictions = model(input_eval) #we can do this cuz of shape of embedding layer

    predictions = tf.squeeze(predictions,0)

    predictions = predictions/temperature

    predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

    input_eval = tf.expand_dims([predicted_id],0)

    text_generated.append(ind_to_char[predicted_id])

  return(start_seed+"".join(text_generated))

In [ ]:
print(generate_text(model2,"JULIET",gen_size=1000))

JULIETN. Appress as true, it is not  no leave of my mistress than dead.
  GRUMIO. Here is one of the pair;
    Now bury me to have chidfledge him true
    To have he rotch e.
  PROTEUS. O Jupiter!
    Holy fiery-tyoul plainly.
  ESCALUS. Bid me live again with which lacks more mile, that we may be contedrate
    a flesh-him;
    And leave you your discreate, tears; for the
    strikes are cruel than the poor ocean under whose descended womb
    To grant thee wight, did merry angrary.
  OBERON. Thou wolf

Enter the Duke of Ally-done,
                 and others as Cassalo, above

  LLOND. Saue it not say, and work therein,
    Nor did the rest, and mad'st consent, and a plant it modest even with our king.'
    Nay, come away, and be her bed!
    It is appraising with the bitter GHOSTS. No princely, give me leave to speak with her
    For the flies date proclaim'd the merchant, mangle,
    The other for his own will shake us to it.
  AGUECHEEK. Mayam, madam, if he may be brought in. We a